Feature
BuildForSDG/dijiElimu-Backend pull request #10
Opened 2020-05-18 09:11 UTC by kiminzajnr

**Description**
Add course models
Add course endpoints

2020-05-18 10:00 UTC, Bonifase requested changes

2020-05-18 10:00 UTC, Bonifase commented on course/models.py
> +from django.db import models
Remove this extra import.Otherwise great work.

2020-05-18 10:43 UTC, james-mungai submitted a review, later dismissed

2020-05-18 13:40 UTC, Bonifase submitted a review, later dismissed

2020-05-22 11:11 UTC, atembamanu commented on dijielimu/settings.py
> +SECRET_KEY = 'uq_a%%9v)v=x+u!f09ip3&_t$4wn_vc$ksty4sbjqxw5&@okeh'
Why expose the secret key?

2020-05-22 11:16 UTC, atembamanu submitted a review, later dismissed
Please add unnecessary files to gitignore

2020-05-23 13:21 UTC, Bonifase approved these changes

2020-05-23 13:29 UTC, james-mungai approved these changes

2020-05-24 08:27 UTC, atembamanu approved these changes

2020-05-24 08:28 UTC, merged