relationships:course, dep, units
BuildForSDG/dijiElimu-Backend pull request #20
Opened 2020-06-06 08:08 UTC by kiminzajnr

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-06 08:30 UTC, james-mungai approved these changes

2020-06-06 10:01 UTC, Bonifase requested changes

2020-06-06 10:01 UTC, Bonifase commented on course/models.py
> +    video_id = models.CharField(blank=False, max_length=32)
I don't think the video fields, and departments are necessary for now. The relationships have been defined in the video and course models. You can make student and tutor fields a relationship.

2020-06-07 20:35 UTC, atembamanu approved these changes

2020-06-16 08:05 UTC, closed without merging